"""
Settings for trans girls rule the world
"""
import os

TUMBLR = [
    os.environ['TRANS_GIRLS_CONSUMER_KEY'],
    os.environ['TRANS_GIRLS_CONSUMER_SECRET'],
    os.environ['TRANS_GIRLS_OAUTH_TOKEN'],
    os.environ['TRANS_GIRLS_OAUTH_SECRET']
]

TAGS = [
    'trans girl',
    'trans woman',
    'twoc',
    'girlslikeus'
]

WHITELIST = set([
    'netflixdesign',
    'always-sunny-in-lilydelphia',
    'daily-transitions',
    'terrificallytranstrid',
    'mytitslookgood',
    'naidje',
    'blissfulsomeone',
    'elegant-witch-bitch'
])

BLACKLIST = set([
    "tranny",
    "ladyboy",
    "tgirl",
    "t girl",
    "trap",
    "traps",
    "genderbend",
    "genderbender",
    "genderswap",
    "sissy",
    "shemale",
    "transvesti",
    "transvestite",
    "crossdresser",
    "t-girl",
    "dickgirl",
    "futa",
    "futanari",
    "shim",
    "herm",
    "hermaphrodite",
    "dont reblog",
    "don't reblog",
    "no reblogs",
    "no reblog",
    "don't reblog plz",
    "dont reblog plz",
    "no reblogs plz",
    "no reblog plz",
    "don't reblog pls",
    "dont reblog pls",
    "no reblogs plz",
    "no reblog plz",
    "do not reblog",
    "do not reblog pls",
    "do not reblog plz",
    "nsfw",
    "nudity",
    "nude",
    "lewd",
    "sex",
    "breasts",
    "dick",
    "ass",
    "blood",
    "bloody",
    "cutting",
    "self harm",
    "self-harm",
    "bloodplay",
    "cuts",
    "headcanon",
    "headcanons",
    "trans headcanon",
    "fanart",
    "trans hc",
    "gender hc",
    "hot transgender",
    "trans boy",
    "trans guy"
    "truscum",
    "man",
    "boy",
    "shirtless",
    "topless",
    "comic",
    "webcomic"
])

SAFE_EMOJIS = [
    ':innocent:',
    ':grinning:',
    ':smiley:',
    ':wink:',
    ':blush:',
    ':relaxed:',
    ':yum:',
    ':innocent:',
    ':heart_eyes:',
    ':kissing_heart:',
    ':heartpulse:',
    ':astonished:',
    ':smile_cat:',
    ':heart_eyes_cat:',
    ':ok_woman:',
    ':bow:',
    ':raised_hands:',
    ':eyes:',
    ':thumbsup:',
    ':ok_hand:',
    ':tulip:',
    ':rose:',
    ':bouquet:',
    ':herb:',
    ':leaves:',
    ':rabbit:',
    ':hatching_chick:',
    ':hatched_chick:',
    ':dog:',
    ':gift_heart:',
    ':monkey_face:',
    ':see_no_evil:',
    ':hear_no_evil:',
    ':whale:',
    ':frog:',
    ':octopus:',
    ':sunny:',
    ':star2:',
    ':star:',
    ':stars:',
    ':sunrise:',
    ':tada:',
    ':confetti_ball:',
    ':sparkles:',
    ':two_hearts:',
    ':cupid:',
    ':+1:',
    ':smiley_cat:'
    ':sparkling_heart:',
    ':heart:',
    ':purple_heart:',
    ':yellow_heart:',
    ':green_heart:',
    ':blue_heart:',
    ':dancer:',
    ':snowboarder:',
    ':bangbang:',
    ':exclamation:',
    ':100:'
]
