"""
Settings for trans girls rule the world
"""
import os
BLOG_URL = 'transgirlsruletheworld.tumblr.com'

TUMBLR = [
    os.environ['TRANS_GIRLS_CONSUMER_KEY'],
    os.environ['TRANS_GIRLS_CONSUMER_SECRET'],
    os.environ['TRANS_GIRLS_OAUTH_TOKEN'],
    os.environ['TRANS_GIRLS_OAUTH_SECRET']
]

TAGS = [
    'trans woman',
    'twoc',
    'girlslikeus',
    'transgirlsruletheworld'
]

BLACKLIST = set([
    "ass",
    "anti gender",
    "blood",
    "bloodplay",
    "bloody",
    "boy",
    "boyswillbegirls",
    "breasts",
    "cocksucking",
    "comic",
    "crossdresser",
    "crossdressing",
    "cuts",
    "cutting",
    "daddy",
    "dick",
    "dickgirl",
    "do not reblog",
    "do not reblog pls",
    "do not reblog plz",
    "don't reblog",
    "don't reblog pls",
    "don't reblog plz",
    "dont reblog",
    "dont reblog pls",
    "dont reblog plz",
    "fanart",
    "femboi",
    "fembot",
    "ftm",
    "ftmtransgender",
    "ftm hrt",
    "ftm transgender",
    "ftm transman",
    "futa",
    "futanari",
    "feminization",
    "gay boy",
    "gay boys",
    "gay man",
    "gay men",
    "gender hc",
    "genderbend",
    "genderbender",
    "genderswap",
    "gender critical",
    "gendercritial",
    "he/him",
    "headcanon",
    "herm",
    "hermaphrodite",
    "hot transgender",
    "ladyboy",
    "ladyboys",
    "lewd",
    "lesbian separatism",
    "masturbate",
    "masturbating",
    "menlikeus",
    "mindless",
    "naked",
    "male",
    "male violence against women",
    "millennialradfem"
    "no reblog",
    "no reblog plz",
    "no reblog plz",
    "no reblogs",
    "no reblogs plz",
    "no reblogs plz",
    "nsfw",
    "nude",
    "nudity",
    "pre op ftm",
    "play thing",
    "porn",
    "pro Vagina",
    "pro wombyn born wombyn",
    "radfem",
    "rad feminism",
    "rad feminist",
    "radical feminism",
    "radical feminist",
    "radical feminist theory",
    "self harm",
    "self-harm",
    "sex",
    "sexual",
    "shamala",
    "shamale",
    "shamela",
    "shamele",
    "shemala",
    "shemale",
    "shemela",
    "shemele",
    "shim",
    "shirtless",
    "siss",
    "sissifaction",
    "sissy",
    "terf",
    "terf-safe",
    "terf safe",
    "terfsafe",
    "terf positivity",
    "t girl",
    "t-girl",
    "tgirl",
    "topless",
    "toptrans",
    "tranny",
    "trannywomen",
    "trans boy",
    "trans boys",
    "trans guy",
    "trans hc",
    "trans headcanon",
    "trans masc",
    "trans masculine",
    "trans positivity",
    "trans exclusionary radical feminism",
    "transboy",
    "transboys",
    "transexuals",
    "transguy",
    "transmasc",
    "transmasculine",
    "transsexual",
    "transvesti",
    "transvestite",
    "trap",
    "traps",
    "truscum",
    "transgenderism",
    "webcomic",
    "wombyn born wombyn",
    "xdresser"
])

SAFE_EMOJIS = [
    ':innocent:',
    ':grinning:',
    ':smiley:',
    ':wink:',
    ':blush:',
    ':relaxed:',
    ':yum:',
    ':innocent:',
    ':heart_eyes:',
    ':kissing_heart:',
    ':heartpulse:',
    ':astonished:',
    ':smile_cat:',
    ':heart_eyes_cat:',
    ':ok_woman:',
    ':bow:',
    ':raised_hands:',
    ':eyes:',
    ':thumbsup:',
    ':ok_hand:',
    ':tulip:',
    ':rose:',
    ':bouquet:',
    ':herb:',
    ':leaves:',
    ':rabbit:',
    ':hatching_chick:',
    ':hatched_chick:',
    ':dog:',
    ':gift_heart:',
    ':monkey_face:',
    ':see_no_evil:',
    ':hear_no_evil:',
    ':whale:',
    ':frog:',
    ':octopus:',
    ':sunny:',
    ':star2:',
    ':star:',
    ':stars:',
    ':sunrise:',
    ':tada:',
    ':confetti_ball:',
    ':sparkles:',
    ':two_hearts:',
    ':cupid:',
    ':+1:',
    ':smiley_cat:'
    ':sparkling_heart:',
    ':heart:',
    ':purple_heart:',
    ':yellow_heart:',
    ':green_heart:',
    ':blue_heart:',
    ':dancer:',
    ':snowboarder:',
    ':bangbang:',
    ':exclamation:',
    ':100:'
]
